cloud:
  aws:
    credentials:
      accessKey: AKIA4OHJ6ZJ6H2LDRELQ
      secretKey: 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
    s3:
      bucket: volunteer-project
      folder:
        folderName1: user/
        folderName2: recruitment/
        folderName3: log/
    region:
      static: ap-northeast-2
    stack:
      auto: false