server:
  port: 8888

---
spring:
  datasource:
    diver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/volunteer?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Swagger 버전 이슈

  servlet:
    multipart: #파일 사이즈 제한
      max-file-size: 10MB
      max-request-size: 10MB
